'use strict';var Yea={TAB:0,Nl:1,sq:2},bu=function(){return new rb("MediaRouter.CastStreaming.Session.Launch")},cu=function(){return new xb("MediaRouter.CastStreaming.Session.Length")},du=function(a){Bb("MediaRouter.CastStreaming.Start.Success",a,Yea)};var eu=gb("mr.mirror.cast.LogUploader"),gu=function(a,b,c){fu("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?reportid=&q="+encodeURIComponent("UserComments='"+b+"'"):""},fu=function(a,b,c,d){if(0==b.size)x(eu,"Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,b);c&&e.append("comments",c);Hs("https://clients2.google.com/cr/report",function(f){f=f.target;var g=
null;Ps(f)?(g=Rs(f),x(eu,"Upload to Crash succeeded: "+g)):x(eu,"Upload to Crash failed. HTTP status: "+f.Pa());d&&d(g)},"POST",e,void 0,3E4)}};var hu=function(){this.g=0;Al(this)},ju=function(){iu||(iu=new hu);return iu},Zea=function(){var a=ju(),b={fraction:.01,autoSubmitTimeLimitMillis:6048E5},c=b.autoSubmitTimeLimitMillis,d=Date.now();return a.g&&c&&d-a.g<c?!1:Math.random()<b.fraction};hu.prototype.Ra=function(){return"mirror.cast.LogUtils"};hu.prototype.Jb=function(){return[void 0,{lastAutoSubmitMillis:this.g}]};hu.prototype.Ib=function(){var a=yl(this);this.g=a&&a.lastAutoSubmitMillis||0};var iu=null;gb("mr.mirror.cast.LogUtils");var ku={vB:"OFFER",hx:"ANSWER",XB:"PRESENTATION",ez:"GET_STATUS",kD:"STATUS_RESPONSE",dz:"GET_CAPABILITIES",Fx:"CAPABILITIES_RESPONSE",LC:"RPC"};var $ea=function(){this.capabilities=this.status=this.g=this.error=this.rpc=this.result=this.type=this.h=this.sessionId=null},bfa=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var b;lu(JSON.parse(a),function(d){b=afa(d)},function(){throw Error("non-Object result from JSON parse");});return b}catch(d){var c=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(c+". Input was "+a);},afa=function(a){var b=new $ea;null!=a.sessionId&&(b.sessionId=String(a.sessionId));mu(a.seqNum,function(f){b.h=f},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),d=l(Object.keys(ku)),e=d.next();!e.done;e=d.next())if(ku[e.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(n(atob(a.rpc))).map(function(f){return f.charCodeAt(0)}))}lu(a.error,function(f){b.error=cfa(f)},function(){throw Error('"error" must be an Object');});lu(a.answer,function(f){b.g=dfa(f)},function(){throw Error('"answer" must be an Object');});lu(a.status,function(f){b.status=efa(f)},function(){throw Error('"status" must be an Object');
});lu(a.capabilities,function(f){b.capabilities=ffa(f)},function(){throw Error('"capabilities" must be an Object');});return b},lu=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},mu=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},nu=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(d){return"number"===typeof d})?b(a):c())},ou=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(d){return String(d)})):c())},gfa=function(){this.m=null;this.g=[];this.h=
[];this.j=this.l=this.C=null},dfa=function(a){var b=new gfa;mu(a.udpPort,function(c){b.m=c},function(){throw Error('"answer.udpPort" must be a number');});nu(a.sendIndexes,function(c){b.g=c},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});nu(a.ssrcs,function(c){b.h=c},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.C=String(a.IV));"receiverGetStatus"in a&&(b.l="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(b.j=
String(a.castMode));return b},hfa=function(){this.details=this.description=this.code=null},cfa=function(a){var b=new hfa;mu(a.code,function(c){b.code=c},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));lu(a.details,function(c){b.details=c},function(){throw Error('"error.details" must be an Object');});return b},ifa=function(){this.h=this.g=null},efa=function(a){var b=new ifa;mu(a.wifiSnr,function(c){b.g=c},function(){throw Error('"status.wifiSnr" must be a number');
});nu(a.wifiSpeed,function(c){b.h=c},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},jfa=function(){this.h=this.g=null},ffa=function(a){var b=new jfa;ou(a.mediaCaps,function(c){b.g=c},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.h=a.map(function(c){var d;lu(c,function(e){d=kfa(e)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return d})}return b},lfa=function(){this.j=this.o=this.C=this.m=this.F=this.g=this.s=this.h=this.initDataTypes=this.l=null},kfa=function(a){var b=new lfa;"keySystemName"in a&&(b.l=String(a.keySystemName));ou(a.initDataTypes,function(c){b.initDataTypes=c},function(){throw Error('"capabilities.initDataTypes" must be an array');});ou(a.codecs,function(c){b.h=c},function(){throw Error('"capabilities.codecs" must be an array');});ou(a.secureCodecs,function(c){b.s=c},function(){throw Error('"capabilities.secureCodecs" must be an array');
});ou(a.audioRobustness,function(c){b.g=c},function(){throw Error('"capabilities.audioRobustness" must be an array');});ou(a.videoRobustness,function(c){b.F=c},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.m=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.C=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.o=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.j=String(a.distinctiveIdentifierSupport));return b};var pu=function(a){this.u=gb("mr.mirror.cast.MessageDispatcher");this.l=a;this.g=null;this.h=new Map;this.j=0};pu.prototype.subscribe=function(a,b){if(this.h.has(a))throw Error("Attempt to multiple-subscribe to the same response type: "+a);this.h.set(a,b);this.j=0;nb(this.u,"Added subscriber for "+a+"-type messages.");this.g||(this.g=tt(this.l),this.g.onMessage=this.m.bind(this))};
var qu=function(a,b){a.h.delete(b)&&nb(a.u,function(){return"Removed subscriber of "+b+"-type messages."});0==a.h.size&&a.g&&(a.g.Wa(),a.g=null)};pu.prototype.sendMessage=function(a){return this.g?"RPC"==a.type?this.g.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.g.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var ru=function(a,b,c,d,e){var f=null,g=function(){qu(a,c);null!=f&&(clearTimeout(f),f=null)};try{a.subscribe(c,function(k){e(k)&&g()})}catch(k){e(null,k);return}f=setTimeout(function(){g();e(null,Error("timeout"))},d);a.sendMessage(b).catch(function(k){g();e(null,k)})};
pu.prototype.m=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var b=void 0;try{b=bfa(a.data)}catch(d){b=d.message;break}if(b.type){var c=this.h.get(b.type);if(c)try{c(b);return}catch(d){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback was: ")+(d.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);10>
this.j?this.u.M(b):nb(this.u,b);++this.j}};var su=function(){this.g=Promise.resolve(1)},uu=function(a,b,c){return tu(a,function(d){return d==b},c)},mfa=function(a,b){var c=[3,4];return tu(a,function(d){return-1!=c.indexOf(d)},b)},vu=function(a,b){a.g=a.g.catch(function(){return 1});return tu(a,function(){return!0},b)},tu=function(a,b,c){var d,e,f=new Promise(function(g,k){d=g;e=k});a.g=a.g.then(function(g){if(!b(g))return e(Error("Operation requires a different starting checkpoint than "+g)),Promise.resolve(g);var k=new nfa(g);try{var m=c(k)}catch(p){m=
Promise.reject(p)}return m.then(function(p){return d(p)},function(p){return e(p)}).then(function(){if(null===k.g)throw Error("A prior operation that started at "+(g+" did not complete."));return k.g})},function(g){e(g);throw g;});return f},nfa=function(a){this.h=a;this.g=null},wu=function(a,b){a.g="number"===typeof b?b:a.h};var xu=chrome.cast.streaming,yu=gb("mr.mirror.cast.StreamingLaunchWorkflow"),Au=function(a,b,c,d,e){this.L=a.sessionId;this.F=a.dg;this.T=a.ye;this.j=b;this.J=c;this.H=d;this.W=zu(e,"onAnswer",this.F);this.Ta=zu(e,"onSessionStop",this.F);this.u=yu;this.w=new su;this.o=this.G=this.s=this.h=this.g=this.C=this.m=this.l=null};
Au.prototype.start=function(a,b,c){var d=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var e=a instanceof Bu,f=b instanceof Bu;(e&&b&&!f||f&&a&&!e)&&Gb("Mixing remoting and non-remoting tracks");return uu(this.w,1,function(g){d.l=a;d.m=b;d.C=c;x(d.u,function(){return"Launching streaming for "+Cu(d)+" to a "+(d.T+".")});return ofa(d).then(d.K.bind(d)).then(function(k){return pfa(d,k).then(function(m){d.W();var p=qfa(d,m,k);d.g=Du(d,d.g,p);d.h=Du(d,d.h,p);if(!d.g&&!d.h)throw Error("Receiver did not select any offers from: "+
JSON.stringify(k));d.G=!!m.l;d.o=function(u,A){u==d.g?d.C.ef("Audio stream (id="+u+") error: "+A):u==d.h&&d.C.ef("Video stream (id="+u+") error: "+A)};xu.rtpStream.onError.addListener(d.o);return rfa(d,m,p)})}).then(function(){x(d.u,function(){return"Launched streaming for "+Cu(d)});d.C.Ig(d);wu(g,2);return{Lr:d.g,Lw:d.h}})})};
Au.prototype.stop=function(){var a=this;return vu(this.w,function(b){if(!a.l&&!a.m)return wu(b,1),Promise.resolve();x(a.u,function(){return"Stopping streaming for "+Cu(a)+"."});a.o&&(xu.rtpStream.onError.removeListener(a.o),a.o=null);if(a.C){var c=a.C.yh();a.C=null}else c=Promise.resolve();return c.then(function(){a.g&&(xu.rtpStream.stop(a.g),xu.rtpStream.destroy(a.g),a.g=null);a.h&&(xu.rtpStream.stop(a.h),xu.rtpStream.destroy(a.h),a.h=null);a.s&&(xu.udpTransport.destroy(a.s),a.s=null);a.Ta();x(a.u,
function(){return"Stopped streaming for "+Cu(a)+"."});a.l=null;a.m=null;wu(b,1)})})};
var sfa=function(a,b){var c=JSON.stringify(b);return Promise.all([a.g&&new Promise(function(d){return xu.rtpStream.getRawEvents(a.g,c,d)}),a.h&&new Promise(function(d){return xu.rtpStream.getRawEvents(a.h,c,d)})]).catch(function(d){a.u.error("Unexpected error when calling getRawEvents()",d);return[]}).then(function(d){return new Blob(d.filter(function(e){return!!e}),{type:"application/gzip"})})},tfa=function(a){return Promise.all([a.g&&new Promise(function(b){return xu.rtpStream.getStats(a.g,b)}),
a.h&&new Promise(function(b){return xu.rtpStream.getStats(a.h,b)})]).catch(function(b){a.u.error("Unexpected error when calling getStats()",b);return[]}).then(function(b){return Object.assign.apply(Object,[{}].concat(n(b.filter(function(c){return!!c}))))})},Cu=function(a){if(a.l&&a.m)var b="audio+video ";else if(a.l)b="audio-only ";else if(a.m)b="video-only ";else return"stopped";return a.l instanceof Bu||a.m instanceof Bu?b+"remoting":b+"streaming"},ofa=function(a){return new Promise(function(b){var c=
function(d,e,f){d&&!a.l&&(xu.rtpStream.destroy(d),d=null);e&&!a.m&&(xu.rtpStream.destroy(e),e=null);x(a.u,function(){return"Created Cast Streaming session: audioStreamId="+d+", videoStreamId="+e+"."});a.g=d;a.h=e;a.s=f;b()};a.l instanceof Bu||a.m instanceof Bu?xu.session.create(null,null,c):xu.session.create(a.l,a.m,c)})};
Au.prototype.K=function(){for(var a=sj(),b=sj(),c=[],d=l([this.g,this.h]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.g,g=f?127:96,k=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,m=f?48E3:9E4,p=l(xu.rtpStream.getSupportedParams(e)),u=p.next();!u.done;u=p.next())u=u.value,u.payload.payloadType=g,u.payload.maxLatency=this.j.maxLatencyMillis,u.payload.minLatency=this.j.minLatencyMillis,u.payload.animatedLatency=this.j.animatedLatencyMillis,u.payload.ssrc=
k,u.payload.clockRate=m,u.payload.aesKey=a,u.payload.aesIvMask=b,f?(u.payload.channels=2,u.payload.maxBitrate=this.j.audioBitrate,u.payload.maxFrameRate=100):(u.payload.minBitrate=this.j.minVideoBitrate,u.payload.maxBitrate=this.j.maxVideoBitrate,u.payload.maxFrameRate=this.j.maxFrameRate),c.push(new ufa(e,u));return c};
var Du=function(a,b,c){b&&!c.some(function(d){return d.gg==b})&&(a.u.M("Destroying RTP stream not selected by the receiver: id="+b),xu.rtpStream.destroy(b),b=null);return b},pfa=function(a,b){return new Promise(function(c,d){for(var e=[],f=0;f<b.length;++f){var g=b[f].params,k={index:f,codecName:g.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:g.payload.payloadType,ssrc:g.payload.ssrc,targetDelay:g.payload.animatedLatency,aesKey:g.payload.aesKey,aesIvMask:g.payload.aesIvMask,timeBase:"1/"+
g.payload.clockRate,receiverRtcpEventLog:a.j.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.j.dscpEnabled&&(k.receiverRtcpDscp=46);127==g.payload.payloadType?Object.assign(k,{type:"audio_source",bitRate:0<g.payload.maxBitrate?1E3*g.payload.maxBitrate:60*g.payload.maxFrameRate+g.payload.clockRate*g.payload.channels,sampleRate:g.payload.clockRate,channels:g.payload.channels}):Object.assign(k,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*g.payload.maxFrameRate)+"/1000",
maxBitRate:1E3*g.payload.maxBitrate,resolutions:[{width:a.j.maxWidth,height:a.j.maxHeight}]});e.push(k)}var m=a.l instanceof Bu||a.m instanceof Bu?"remoting":"mirroring",p={type:"OFFER",sessionId:a.L,seqNum:tm(a.J),offer:{castMode:m,receiverGetStatus:!0,supportedStreams:e}};x(a.u,function(){return"Sending OFFER message: "+JSON.stringify(p)});ru(a.H,p,"ANSWER",1E4,function(u,A){if(null==u)d(A);else if("ok"==u.result&&u.g){if(u.h!=p.seqNum)return a.u.M("Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(u)),!1;((A=u.g.j)&&A!=m||!A&&"mirroring"!=m)&&a.u.error("Expected receiver to ANSWER with castMode="+m+", but got: "+A);nb(a.u,function(){return"Received ANSWER: "+JSON.stringify(u)});c(u.g)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(u)));return!0})})},qfa=function(a,b,c){if(b.g.length!=b.h.length)return a.u.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(b)),[];for(var d=[],e={},f=0;f<b.g.length;e={tf:e.tf},++f){var g=b.g[f];if(0>g||g>=c.length)return a.u.error("Receiver selected invalid index ("+
g+" < "+c.length+") in ANSWER: "+JSON.stringify(b)),[];e.tf=c[g];if(d.some(function(k){return function(m){return m.gg==k.tf.gg}}(e)))return a.u.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(b)),[];e.tf.params.payload.feedbackSsrc=b.h[g];if(d.some(function(k){return function(m){return m.params.payload.feedbackSsrc==k.tf.params.payload.feedbackSsrc}}(e)))return a.u.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+JSON.stringify(b)),[];d.push(e.tf)}return d},
rfa=function(a,b,c){var d=null,e=function(){d&&(xu.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(f,g){var k=b.m||2344;x(a.u,function(){return"Starting RTP streams to receiver at "+(a.F+":"+k)+(" for selected offers: "+JSON.stringify(c))});var m=a.s||-1;a.j.dscpEnabled&&(x(a.u,"Enabled DSCP in sender."),xu.udpTransport.setOptions(m,{DSCP:!0}));xu.udpTransport.setDestination(m,{address:a.F,port:k});var p=new Set(c.map(function(A){return A.gg}));d=function(A){p.delete(A);
0==p.size&&f()};xu.rtpStream.onStarted.addListener(d);m=l(c);for(var u=m.next();!u.done;u=m.next())u=u.value,xu.rtpStream.toggleLogging(u.gg,a.j.enableLogging),xu.rtpStream.start(u.gg,u.params);setTimeout(function(){g(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(f){e();throw f;})},zu=function(a,b,c){return a&&b in a?function(){try{a[b](c)}catch(d){yu.error("Error from testHooks."+b,d)}}:function(){}},ufa=function(a,b){this.gg=a;this.params=b},Bu=function(){};var Eu=gb("mr.mirror.cast.MediaRemoter"),Fu=function(a,b,c,d,e,f){this.o=a;this.H=vfa(b,this.o.Cb);this.J=new Au(this.o.Cb,c,d,e,f);this.G=e;this.m=new su;this.j=new wfa;this.w=new mojo.Binding(mojo.MirrorServiceRemoter,this,null);this.u=Eu;this.F=this.g=this.C=this.l=this.K=null;this.h=!0;this.s=this.L.bind(this)};
Fu.prototype.initialize=function(a,b){var c=this;return uu(this.m,1,function(d){c.K=a;c.l=b;var e=c.w.createInterfacePtrAndBind();c.w.setConnectionErrorHandler(function(){x(c.u,"Remoter mojo pipe connection error.");Gu(c)});c.g=new mojo.MirrorServiceRemotingSourcePtr;var f=zaa(c.o.mediaSource||"");if(!f)throw Error("Failed to parse tab ID from source:\n          "+c.o.mediaSource);x(c.u,"Connecting remoter to browser: tabId="+f);(Hi.get("mr.ProviderManager")||null).onMediaRemoterCreated(f,e,mojo.makeRequest(c.g));
c.g.ptr.setConnectionErrorHandler(function(){x(c.u,"RemotingSource mojo pipe connection error.");Gu(c)});return xfa(c).then(function(){if(c.h)c.g.onSinkAvailable(c.H);wu(d,2)})})};
var Gu=function(a){return vu(a.m,function(b){a.g&&(a.g.ptr.reset(),a.g=null);var c=a.C;a.C=null;a.l=null;a.K=null;a.w.close();chrome.settingsPrivate.onPrefsChanged.hasListener(a.s)&&chrome.settingsPrivate.onPrefsChanged.removeListener(a.s);return new Promise(function(d){window.setTimeout(function(){Hu(a).then(function(){wu(b,1);d();c&&c()})},250)})})};h=Fu.prototype;h.Uv=function(a){Iu(this.j,a)};h.Ig=function(a){this.l&&this.l.Ig(a)};h.yh=function(){return this.l?this.l.yh():Promise.resolve()};
h.ef=function(a,b){this.u.error("Error during streaming: "+a,b);if(this.g)this.g.onError();Gu(this)};
h.start=function(){var a=this,b=!1;x(this.u,function(){b=!0;return"Starting next media remoting session."});b&&yfa(this.j,function(c){return x(a.u,c)});zfa(this.j);uu(this.m,2,function(c){return(0,a.K)().then(function(d){a.C=d;a.G.subscribe("RPC",function(e){if(e.rpc){var f=a.j;e=e.rpc;f.C&&(++f.o,f.h+=e.length,f.C(e))}});wu(c,3)}).catch(function(d){return Hu(a).then(function(){wu(c);throw d;})})}).then(function(){x(a.u,"Remoting started successfully.")}).catch(function(c){a.u.error("Failed to start remoting",
c);a.g.onError()})};h.tw=function(a,b){var c=this;return uu(this.m,3,function(d){return c.J.start(a?new Bu:null,b?new Bu:null,c).then(function(e){Afa(c.j,function(f){return c.G.sendMessage(f)},function(f){c.g.onMessageFromSink(f)});wu(d,4);return{audio_stream_id:e.Lr||-1,video_stream_id:e.Lw||-1}}).catch(function(e){return Hu(c).then(function(){wu(d);throw e;})})}).catch(function(d){c.u.error("Failed to start remoting streams",d);Gu(c);return{audio_stream_id:-1,video_stream_id:-1}})};
h.stop=function(a){var b=this;mfa(this.m,function(c){b.g.onStopped(a);return Hu(b).then(function(){x(b.u,"Remoting stopped.");wu(c,5);(0,b.C)().then(function(){return uu(b.m,5,function(d){if(b.g&&b.h)b.g.onSinkAvailable(b.H);wu(d,2);return Promise.resolve()})}).catch(function(d){throw d;});b.C=null})}).catch(function(c){b.u.error("Failed to stop remoting: ",c);Gu(b)})};
h.ts=function(){null===this.F&&(this.F=vf(this.o.Cb.dg).then(function(a){return a.h||!1}));return this.F.then(function(a){return{rate:(a?1E7:5E6)/8}})};
var Hu=function(a){return a.J.stop().then(function(){qu(a.G,"RPC");Bfa(a.j);Ju(a.j)})},xfa=function(a){return new Promise(function(b){chrome.settingsPrivate.getPref("media_router.media_remoting.enabled",function(c){chrome.runtime.lastError?a.u.error("Encountered error getting media remoting pref: "+JSON.stringify(chrome.runtime.lastError)):c.type!=chrome.settingsPrivate.PrefType.BOOLEAN?a.u.error("Pref value not a boolean: "+JSON.stringify(c)):(a.h=!!c.value,x(a.u,"Initializing mediaRemotingEnabled_ with value read from pref: "+
a.h));chrome.settingsPrivate.onPrefsChanged.hasListener(a.s)||chrome.settingsPrivate.onPrefsChanged.addListener(a.s);b()})})};
Fu.prototype.L=function(a){if(this.g){a=l(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value,"media_router.media_remoting.enabled"==b.key){if(b.type!=chrome.settingsPrivate.PrefType.BOOLEAN){this.u.error("Pref value not a boolean: "+JSON.stringify(b));break}a=!!b.value;if(this.h==a)break;this.h=a;x(this.u,"mediaRemotingEnabled_ changed to: "+this.h);if(this.h)this.g.onSinkAvailable(this.H);else this.g.onStopped(mojo.RemotingStopReason.USER_DISABLED);break}}};
var vfa=function(a,b){var c=new mojo.RemotingSinkMetadata;c.features=[];c.friendly_name=b.ow||"";c.audio_capabilities=[];c.video_capabilities=[];var d=mojo.RemotingSinkAudioCapability,e=mojo.RemotingSinkVideoCapability,f=c.audio_capabilities,g=c.video_capabilities,k=b.ye||"";(a.g||[]).forEach(function(m){switch(m){case "audio":f.push(d.CODEC_BASELINE_SET);break;case "aac":f.push(d.CODEC_AAC);break;case "opus":f.push(d.CODEC_OPUS);break;case "video":g.push(e.CODEC_BASELINE_SET);break;case "4k":g.push(e.SUPPORT_4K);
break;case "h264":g.push(e.CODEC_H264);break;case "vp8":g.push(e.CODEC_VP8);break;case "vp9":k.startsWith("Chromecast Ultra")&&g.push(e.CODEC_VP9);break;case "hevc":k.startsWith("Chromecast Ultra")&&g.push(e.CODEC_HEVC);break;default:x(Eu,"Unknown mediaCap name: "+m)}});b.ye&&"Chromecast Ultra"==b.ye&&g.push(e.SUPPORT_4K);return c};Fu.prototype.estimateTransmissionCapacity=Fu.prototype.ts;Fu.prototype.stop=Fu.prototype.stop;Fu.prototype.startDataStreams=Fu.prototype.tw;Fu.prototype.start=Fu.prototype.start;
Fu.prototype.sendMessageToSink=Fu.prototype.Uv;
var wfa=function(){this.C=this.m=this.g=null;this.F=this.h=this.o=this.j=this.s=0;this.l=null},zfa=function(a){a.g=[];Ku(a,performance.now())},Afa=function(a,b,c){a.m=b;a.C=c;a.g?(b=a.g,a.g=null,b.forEach(function(d){return Iu(a,d.data).then(d.Wv,d.So)})):Ku(a,performance.now())},Bfa=function(a){if(a.g){var b=Error("Stop before delivering pending message");a.g.forEach(function(c){return c.So(b)});a.g=null}a.m=null;a.C=null},Iu=function(a,b){if(a.m){var c=btoa(String.fromCharCode.apply(null,b));++a.s;
a.j+=b.length;return a.m({type:"RPC",rpc:c})}return a.g?new Promise(function(d,e){a.g.push({data:b,Wv:d,So:e})}):Promise.reject(Error("RPC pipe not started"))},yfa=function(a,b){Ju(a);a.l=setInterval(function(){if(a.g)var c=a.g.length+" messages are waiting to send.";else{c=performance.now();var d=(c-a.F)/1E3;d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.s+" messages ("+Math.round(a.j/d)+" bytes/sec) and received ")+(a.o+" messages ("+Math.round(a.h/d)+" bytes/sec).");Ku(a,c);c=d}b(c)},3E4)},
Ju=function(a){null!=a.l&&(clearInterval(a.l),a.l=null)},Ku=function(a,b){a.s=0;a.j=0;a.o=0;a.h=0;a.F=b};var Cfa=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},Dfa=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var Lu=function(a,b,c,d,e){this.j=new Au(a,b,c,d,void 0===e?null:e);this.u=gb("mr.mirror.cast.MediaStreamer");this.m=new su;this.l=this.h=this.g=this.C=null};Lu.prototype.start=function(a,b){var c=this;return uu(this.m,1,function(d){c.C=a;c.g=Cfa(a);c.g&&"ended"==c.g.readyState&&(c.g=null);c.h=Dfa(a);c.h&&"ended"==c.h.readyState&&(c.h=null);if(!c.g&&!c.h)return wu(d),Promise.reject(Error("No MediaStream tracks to stream."));c.l=b;return c.j.start(c.g,c.h,c.l).then(function(){return wu(d,2)})})};
Lu.prototype.stop=function(){var a=this;return vu(this.m,function(b){return a.j.stop().then(function(){a.g=null;a.h=null;a.C=null;a.l=null;wu(b,1)})})};var Efa=function(a){return uu(a.m,2,function(b){x(a.u,"Suspending media streaming...");return a.j.stop().then(function(){x(a.u,"Suspended media streaming.");wu(b,3)})})};
Lu.prototype.resume=function(){var a=this;return uu(this.m,3,function(b){a.g&&"ended"==a.g.readyState&&(a.g=null);a.h&&"ended"==a.h.readyState&&(a.h=null);if(!a.g&&!a.h)return Promise.reject(Error("Cannot resume: All tracks have ended."));x(a.u,"Resuming media streaming...");return a.j.start(a.g,a.h,a.l).then(function(){x(a.u,"Resumed media streaming.");wu(b,2)})})};var Mu=function(a,b,c){this.m=a;this.l=b;this.j=c;this.u=gb("mr.mirror.cast.WifiStatusMonitor");this.g=null;this.h=[]};Mu.prototype.start=function(){var a=this;null==this.g&&(nb(this.u,"Starting Wifi Status Monitoring."),this.h=[],this.j.subscribe("STATUS_RESPONSE",function(b){return Ffa(a,b)}),this.g=setInterval(function(){return Nu(a)},12E4),Nu(this))};Mu.prototype.stop=function(){null!=this.g&&(nb(this.u,"Stopping Wifi Status Monitoring."),clearInterval(this.g),this.g=null,qu(this.j,"STATUS_RESPONSE"))};
var Ffa=function(a,b){if(null!=a.g)if(b.status){var c={};null!=b.status.g&&(c.wifiSnr=b.status.g);null!=b.status.h&&(c.wifiSpeed=b.status.h[3]);0==Object.keys(c).length?a.u.M(function(){return"No status fields populated in response: "+JSON.stringify(b)}):(c.timestamp=Date.now(),30==a.h.length&&a.h.shift(),a.h.push(c),x(a.u,function(){return"Current Wifi status: "+JSON.stringify(c)}))}else a.u.M(function(){return"Ignoring response without status: "+JSON.stringify(b)})},Nu=function(a){a.j.sendMessage({type:"GET_STATUS",
sessionId:a.m,seqNum:tm(a.l),get_status:["wifiSnr","wifiSpeed"]})};var Ou=function(a,b,c,d){this.H=b.dg;this.o={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:dj(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:b.ye};this.K=c;this.G=d;this.l=this.h=this.s=this.C=this.m=this.F=this.j=null;this.g=[]};Ou.prototype.Ig=function(a){null!=this.h&&clearInterval(this.h);this.j=a;this.F=Date.now();this.h=setInterval(this.w.bind(this,a),9E5)};
Ou.prototype.yh=function(){null!=this.h&&(clearInterval(this.h),this.h=null);if(null!=this.j){var a=this.w(this.j);this.j=null;return a}return Promise.resolve()};Ou.prototype.ef=function(a,b){null==this.m&&(this.m=Date.now(),"function"===typeof a?this.C=a():"string"===typeof a&&(this.C=a),b&&"string"===typeof b.stack&&(this.s=b.stack))};
var Gfa=function(a,b){return(null==a.j?Promise.resolve():a.w(a.j)).then(function(){var c=b.map(function(d){d=Pu(a,d);var e=d.map(function(g){return g.events}).filter(function(g){return null!=g}),f=["["];d.map(function(g){return g.fg}).forEach(function(g,k){0<k&&f.push(",");f.push(g)});f.push("]");return{events:new Blob(e,{type:"application/gzip"}),fg:new Blob(f,{type:"application/json"})}});a.g=[];return c})};
Ou.prototype.w=function(a){var b=this;if(null!=this.l)return this.l;var c=vf(this.H).then(function(d){d={receiverVersion:d.g,receiverConnected:d.l,receiverOnEthernet:d.h,receiverHasUpdatePending:d.j,receiverUptimeSeconds:d.m};Object.assign(d,b.o);var e=Date.now();Object.assign(d,{startTime:b.F,endTime:e,activity:Cu(a),receiverWifiStatus:Array.from(b.G.h)});b.F=e;null!=b.m&&(Object.assign(d,{streamingErrorTime:b.m,streamingErrorMessage:b.C,streamingErrorCause:b.s}),b.m=null,b.C=null,b.s=null);return d});
return(this.l=Promise.all([c.then(function(d){return sfa(a,d)}),c,tfa(a)]).then(function(d){var e=l(d);d=e.next().value;var f=e.next().value;e=e.next().value;b.g.push({events:d,fg:new Blob([JSON.stringify(Object.assign({tags:f},e))],{type:"application/json"})});b.g=Pu(b,b.K);b.l=null}))||Promise.resolve()};
var Pu=function(a,b){b-=2;for(var c=[],d=a.g.length-1;0<=d;--d){b-=a.g[d].fg.size+1;if(0>b)break;c.push({events:null,fg:a.g[d].fg});if(null!=a.g[d].events){var e=a.g[d].events.size;b>=e&&(c[c.length-1].events=a.g[d].events,b-=e)}}return c.reverse()};var Qu=gb("mr.NetworkUtils"),Ru=function(a,b){if(!qaa)return Promise.reject("TDLS feature not enabled.");x(Qu,"setTDLSState_: ip="+a+", state="+b);return new Promise(function(c,d){chrome.networkingPrivate.setWifiTDLSEnabledState(a,b,function(e){chrome.runtime.lastError?(Qu.M("Unable to set TDLS state: state = "+b+", error = "+chrome.runtime.lastError.message),d("Unable to set TDLS state to "+b+".")):(x(Qu,"TDLS state changed: state = "+b+", status = "+e),c(e))})})};var Su=function(a,b,c,d){d=void 0===d?null:d;aj.call(this,b);var e=b.Cb;this.G=e.sessionId;this.L=e.dg;this.w=a;this.T=d;this.u=gb("mr.mirror.cast.Session");this.F=new su;this.s=new sm("mirror.cast.SeqNumGenerator");this.o=new pu(b.id);this.C=new Lu(e,this.w,this.s,this.o,this.T);this.m=null;this.g=new Ou(a,e,c,new Mu(this.G,this.s,this.o));this.l=!1;this.K=null};q(Su,aj);h=Su.prototype;
h.start=function(a){var b=this;return uu(this.F,1,function(c){var d=bu();return Hfa(b).then(function(e){b.l=e;return b.C.start(a,b)}).then(function(){if(b.C.j.G){var e=b.g;e.o.tdlsIsOn=b.l;e.G.start();Ifa(b)}else b.g.o.tdlsIsOn=b.l;d.end();b.K=cu();wu(c,2);return b})})};
h.stop=function(){var a=this;return vu(this.F,function(b){a.K&&(a.K.end(),a.K=null);a.g.G.stop();return a.C.stop().then(function(){return a.m?Gu(a.m):Promise.resolve()}).then(function(){a.m=null;return a.l?Jfa(a):Promise.resolve()}).then(function(){a.l=!1;wu(b,4)})})};
h.Qo=function(){var a=this,b={sessionId:this.G,seqNum:tm(this.s),type:"PRESENTATION",icons:[],title:Caa(this.Cc)};x(this.u,"Sending session metadata update to receiver: "+this.G);this.o.sendMessage(b).catch(function(c){a.u.M("Failed to send activity to sink: "+c.message)})};h.Ig=function(a){this.g.Ig(a)};h.yh=function(){return this.g.yh()};h.ef=function(a,b){this.g.ef(a,b);this.u.error(a,b);this.stop()};
var Tu=function(a,b){return Gfa(a.g,b)},Hfa=function(a){x(a.u,"maybeEnableTdls_: useTdls = "+a.w.useTdls);return a.w.useTdls?Ru(a.L,!0).then(function(b){if("Connected"==b)return x(a.u,"Successfully enabled TDLS."),!0;a.u.M("Did not enable TDLS: result="+b);return!1}).catch(function(b){a.u.M("Error while calling enableTDLS()",b);return!1}):Promise.resolve(!1)},Jfa=function(a){return Ru(a.L,!1).catch(function(b){return a.u.error("Error while turning TDLS back off",b)})},Ifa=function(a){Kfa(a).then(function(b){(b.g||
[]).includes("video")?Lfa(a,b):a.u.M(function(){return"Receiver incapable of Media Remoting: "+JSON.stringify(b)})}).catch(function(b){a.u.M("None/Invalid capabilites response. Media Remoting disabled.",b)})},Kfa=function(a){return new Promise(function(b,c){var d={type:"GET_CAPABILITIES",sessionId:a.G,seqNum:tm(a.s)};x(a.u,function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});ru(a.o,d,"CAPABILITIES_RESPONSE",3E4,function(e,f){if(null==e)return c(f),!0;if("ok"!=e.result||!e.capabilities)return c(Error("Bad response: "+
JSON.stringify(e))),!0;if(e.h!=d.seqNum)return x(a.u,function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+JSON.stringify(e)}),!1;nb(a.u,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});b(e.capabilities);return!0})})},Lfa=function(a,b){uu(a.F,2,function(c){var d=a.h.Cb.ye||"<UNKNOWN>";if(!d.startsWith("Chromecast")&&!d.startsWith("Eureka Dongle"))return a.u.M('HACK: Media Remoting disabled because the receiver model--"'+(d+'" according to discovery--is not a Chromecast.')),
wu(c),Promise.resolve();a.m=new Fu(a.h,b,a.w,a.s,a.o,a.T);return a.m.initialize(a.W.bind(a),a).catch(function(e){a.u.error("Media Remoting start failed: "+e.message,e)}).then(function(){return wu(c)})})};Su.prototype.W=function(){var a=this;return uu(this.F,2,function(b){return new Promise(function(c,d){Efa(a.C).then(function(){wu(b,3);a.H=!0;Vi(a);c(a.Ta.bind(a))}).catch(function(e){a.ef("Failed to suspend MediaStreamer before starting remoting",e);d(e)})})})};
Su.prototype.Ta=function(){var a=this;return uu(this.F,3,function(b){return new Promise(function(c,d){a.C.resume().then(function(){wu(b,2);a.H=!1;Vi(a);c()}).catch(function(e){a.ef("Failed resume MediaStreamer after ending remoting mode",e);d(e)})})})};var Uu=function(){Ti.call(this,"cast_streaming");this.C=this.F=this.H=this.K=this.l=null;this.aa=this.J="";this.fa=this.s=!1;this.jc=this.ya.bind(this);this.L=this.T=this.W=this.Ta=this.m=null};q(Uu,Ti);h=Uu.prototype;h.Jg=function(a){this.s=a||!1;this.fa=!0};h.getName=function(){return"cast_streaming"};
h.sk=function(a,b,c,d,e){var f=this;if(!this.s)return Ti.prototype.sk.call(this,a,b,c,d,e);x(this.V,"Start mirroring on route "+a.id);if(!this.fa)return qi(Error("Not initialized"));var g=new Promise(function(k,m){f.o().then(function(){if(Si(b)&&c.shouldCaptureVideo)return Ei(!1).then(function(p){f.aa=p})}).then(function(){return e?e(a).g:a}).then(function(p){f.J=b;Mfa(f,p);var u=f.K.createInterfacePtrAndBind(),A=f.H.createInterfacePtrAndBind(),B=Nfa(p,c);Ofa(f,p,b,d);if(!f.l)throw new ui("Error to get mirroring service host");
f.F=new mojo.MirroringCastMessageChannelPtr;f.Ta=bu();f.l.start(B,u,A,mojo.makeRequest(f.F));f.m=new aj(a,f.j.T.bind(f.j));Vi(f.m);Pfa(f,p,b);f.T=function(){return k(p)};f.L=m}).catch(function(p){f.V.error("Mirroring launch error: "+p);f.Yf(void 0===p.reason?9:p.reason);m(p)})});return ri(g)};h.Qh=function(a,b){return new Su(a,b,20969472,null)};h.th=function(){du(0)};h.qh=function(){du(1)};h.yi=function(){du(2)};h.rh=function(){Ab("MediaRouter.CastStreaming.Session.End")};
h.Yf=function(a){Bb("MediaRouter.CastStreaming.Start.Failure",a,ti)};h.sh=function(){Ab("MediaRouter.CastStreaming.Stream.End")};
h.ij=function(a){var b=this;return this.s?Promise.resolve():(new Promise(function(c){return chrome.metricsPrivate.getIsCrashReportingEnabled(c)})).then(function(c){var d=c&&Zea(),e=[9351424];d&&e.push(20969472);return Tu(a,e).then(function(f){var g=f[f.length-1];f=Hl(f[0].events).catch(function(k){b.V.error("Failed to persist events Blob.",k)});d&&0<g.events.size?gu(g.events,void 0,b.uu.bind(b)):c&&fu("stats.json",g.fg,void 0,void 0);return f})})};
h.uu=function(a){if(a){a=ju();var b=Date.now();a.g=b}};h.rk=function(a){if(this.s)return db();x(this.V,"Received message to upload logs for "+a);return this.g?Tu(this.g,[20969472]).then(function(b){b=l(b).next().value;return 0==b.events.size?"":gu(b.events,a)}):Promise.resolve(Qfa(this,a))};
var Qfa=function(a,b){var c=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==c||1>c.length)c=null;else{for(var d=new Uint16Array(c.length),e=0;e<c.length;++e)d[e]=c.charCodeAt(e);c=d.buffer;d=(new Uint8Array(c,c.byteLength-1,1))[0];c=new Uint8Array(c,0,c.byteLength-(0==d?2:1));c=new Blob([c],{type:"application/gzip"})}if(null!=c&&0!=c.size)return Hl(new Blob),x(a.V,"Uploading saved logs for feedback."),gu(c,b)};h=Uu.prototype;
h.onError=function(a){this.L&&(this.L(a),this.T=this.L=null,this.Yf(9));x(this.V,"Mirroring service error: "+a);this.o()};h.didStart=function(){this.T&&(this.T(),this.T=this.L=null);this.Ta&&(this.Ta.end(),this.Ta=null);this.W=cu();Ri(this.J)?this.th():Si(this.J)?this.qh():Pi(this.J)&&this.yi()};h.didStop=function(){this.o()};h.send=function(a){if(this.C){var b=JSON.parse(a.jsonFormatData);nb(this.V,function(){return"Sending message: "+JSON.stringify(b)});this.C.sendMessage(a.jsonFormatData,{namespace:a.messageNamespace})}};
h.vu=function(a){if(a&&(a.namespace_===mojo.MirroringWebRtcNamespace||a.namespace_===mojo.MirroringRemotingNamespace)&&this.F){var b=new mojo.MirroringCastMessage;b.messageNamespace=a.namespace_;"string"!==typeof a.data?x(this.V,"Received non-string as JSON"):(b.jsonFormatData=a.data,this.F.send(b))}};
var Mfa=function(a,b){a.K=new mojo.Binding(mojo.MirroringSessionObserver,a,null);a.H=new mojo.Binding(mojo.MirroringCastMessageChannel,a,null);a.C=tt(b.id);a.C.onMessage=a.vu.bind(a)},Nfa=function(a,b){var c=new mojo.MirroringSessionParameters;c.receiverAddress=new mojo.IPAddress;c.receiverAddress.addressBytes=a.Cb.dg.split(".").map(function(d){return parseInt(d,10)});c.receiverModelName=a.Cb.ye;c.type=b.shouldCaptureVideo&&b.shouldCaptureAudio?mojo.MirroringSessionType.AUDIO_AND_VIDEO:b.shouldCaptureVideo?
mojo.MirroringSessionType.VIDEO_ONLY:mojo.MirroringSessionType.AUDIO_ONLY;return c},Ofa=function(a,b,c,d){a.l=new mojo.MirroringServiceHostPtr;b=b.Cb.tabId||-1;Ri(c)?a.j.getMirroringServiceHostForTab(b,mojo.makeRequest(a.l)):Si(c)?a.j.getMirroringServiceHostForDesktop(-1,a.aa,mojo.makeRequest(a.l)):Pi(c)?(b=new mojo.Url,b.url=c,a.j.getMirroringServiceHostForOffscreenTab(b,d||"",mojo.makeRequest(a.l))):a.l=null},Pfa=function(a,b,c){Ri(c)&&!chrome.tabs.onUpdated.hasListener(a.jc)&&chrome.tabs.onUpdated.addListener(a.jc);
(Ri(c)||Pi(c))&&Xi(a.m,b.Cb.tabId)};Uu.prototype.ya=function(a,b,c){Oi(14);this.m&&Zi(this.m,a,b,c)};
Uu.prototype.o=function(){chrome.tabs.onUpdated.removeListener(this.jc);return this.s?this.fa?this.l?(this.l.ptr.reset(),this.F=this.l=null,this.C&&this.C.Wa(),this.C=null,this.K&&(this.K.close(),this.K=null),this.H&&(this.H.close(),this.H=null),Yi(this.j,this.m.h.id),this.m=null,this.aa=this.J="",this.W&&(this.W.end(),this.W=null),this.rh(),Promise.resolve(!0)):Promise.resolve(!1):Promise.reject("Not initialized"):Ti.prototype.o.call(this)};
Uu.prototype.tk=function(a,b,c,d,e,f){return this.s?qi(Error("Mirroring service does not support updating stream")):Ti.prototype.tk.call(this,a,b,c,d,e,f)};Uu.prototype.send=Uu.prototype.send;Uu.prototype.didStop=Uu.prototype.didStop;Uu.prototype.didStart=Uu.prototype.didStart;Uu.prototype.onError=Uu.prototype.onError;var Rfa=new Uu;Mi("mr.mirror.cast.Service",Rfa);
